- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    nginx_proxy_hosts:
      - { 
          host: fred.smith.bz, 
          aliases: [derf.us, fredsmith.us, fredsmith.org, fredsmith.net, www.derf.us, www.fredsmith.us, www.fredsmith.net, www.fredsmith.org], 
          repo: "https://github.com/fredsmith/fredsmith.github.com.git",
          ssl: true,
          php: true

      }
      - { 
          host: git.smith.bz, 
          backend: "http://10.7.0.102:3001",
          aliases: [git.derf.us, git.fredsmith.org, git.smithfamily.io]
      }
      - { 
          host: jedigurl.com, 
          aliases: [ jessica.smith.bz ],
          repo: "http://deploy:ceylf2Sleca@git.smith.bz/jedigurl/jedigurl.com.git",
          php: true
      }
      - { host: andrew.smith.bz }
      - { host: sean.smith.bz }
      - { host: nathan.smith.bz }
  roles:
    - base
    - nginx_proxy

