- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    nginx_default_redirect_url: "https://www.smith.bz/"
    nginx_default_hostname: 'pandora.smith.bz'
    nginx_proxy_hosts:
      fred.smith.bz:
        aliases: [derf.us, fredsmith.us, fredsmith.org, fredsmith.net, www.derf.us, www.fredsmith.us, www.fredsmith.net, www.fredsmith.org] 
        repo: "https://{{ GIT_CREDENTIALS }}@git.smith.bz/derf/fred.smith.bz.git"
        ssl: true
        indexes: true
        php: true
      home.smith.bz:
        repo: "https://{{ GIT_CREDENTIALS }}@git.smith.bz/derf/managethis.git"
        auth: true
      router.smith.bz:
        backend: "https://10.7.0.1:443"
        ssl: true
      irc.smith.bz:
        backend: "http://10.7.0.82:3008"
        ssl: true
      homeassistant.smith.bz:
        backend: "http://10.7.0.85:8123"
        ssl: true
        auth: true
      vera.smith.bz:
        backend: "http://10.7.0.16:80"
        ssl: true
        auth: true
      git.smith.bz:
        backend: "http://10.7.0.84:3001"
        ssl: true
        aliases: [git.derf.us, git.fredsmith.org, git.smithfamily.io]
      plex.smith.bz:
        backend: "http://10.7.0.85:32400"
        ssl: true
        auth: true
      downloads.smith.bz:
        backend: "http://10.7.0.82:3010"
        ssl: true
        auth: true
      tv.smith.bz:
        backend: "http://10.7.0.81:3009"
        ssl: true
        auth: true
      graphs.smith.bz:
        ssl: true
        auth: true
        backend: "http://10.7.0.81:3005"
      solar.smith.bz:
        ssl: true
        auth: true
        backend: "http://10.7.0.15:80"
      monitoring.smith.bz:
        ssl: true
        auth: true
        backend: "http://10.7.0.85:9090"
      containers.smith.bz:
        backend: "http://10.7.0.85:3007"
        ssl: true
        aliases: [containers.derf.us, containers.fredsmith.org, containers.smithfamily.io]
      jedigurl.com:  
        aliases: [ www.jedigurl.com, jessica.smith.bz ]
        repo: "https://{{ GIT_CREDENTIALS }}@git.smith.bz/jedigurl/jedigurl.com.git"
        php: true
        ssl: true
      andrew.smith.bz:
        aliases: [ andrew.smithfamily.io, andrew.smith.bz ]
        repo: "https://{{ GIT_CREDENTIALS }}@git.smith.bz/derf/andrew.smith.bz.git"
        ssl: true
      sean.smith.bz:
        aliases: [ sean.smithfamily.io, sean.smith.bz ]
        ssl: true
        repo: "https://{{ GIT_CREDENTIALS }}@git.smith.bz/derf/sean.smith.bz.git"
      nathan.smith.bz:
        aliases: [ nathan.smithfamily.io, nathan.smith.bz ]
        ssl: true
        repo: "https://{{ GIT_CREDENTIALS }}@git.smith.bz/derf/nathan.smith.bz.git"
      files.derf.us:
        aliases: [ files.fred.smith.bz ]
        ssl: true
        owner: "derf"
        repo: "https://{{ GIT_CREDENTIALS }}@git.smith.bz/derf/files.derf.us.git"
      smith.bz:
        aliases: [ smithfamily.io, www.smith.bz, fredandjess.com, jessandfred.com, www.fredandjess.com, www.jessandfred.com, www.smithfamily.io, www.smithfamily.space ]
        ssl: true
        repo: "https://{{ GIT_CREDENTIALS }}@git.smith.bz/derf/smith.bz.git"
     
  roles:
    - base
    - nginx_proxy

