- name: Configure telegraf monitoring agent
  hosts: all
  sudo: True
  gather_facts: True
  roles:
    - telegraf
  vars:
    telegraf_influxdb_urls:
      - http://10.7.0.81:8086
    telegraf_plugins_enabled:
      - cpu
      - disk
      - io
      - mem
      - swap
      - system
      - net
      - docker
