docker_repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
docker_repo_key_id: "58118E89F3A912897C070ADBF76221572C52609D"
docker_repo_keyserver: "hkp://p80.pool.sks-keyservers.net:80"

docker_required_packages:
  - linux-image-virtual 
  - linux-image-extra-virtual
docker_packages:
  - docker-engine
