  - name: "install prereqs"
    apt: 
      pkg: "{{ item }}"
      state: latest
    sudo: yes 
    with_items: docker_required_packages
    register: reboot_required

  - name: restart machine
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true
    when: reboot_required.changed
 
  - name: add docker apt repo key
    apt_key:
      id: "{{ docker_repo_key_id }}"
      keyserver: "{{ docker_repo_keyserver }}"
 
  - name: add docker apt repository
    apt_repository:
      repo: "{{ docker_repo }}"

  - name: install packages
    apt: 
      pkg: "{{ item }}" 
      state: latest
    sudo: yes 
    with_items: docker_packages
    register: restart_docker

  - name: create docker service override directory
    file:
      path: "/etc/systemd/system/docker.service.d"
      state: directory
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: configure docker swarm
    template:
      src: override.conf.j2
      dest: "/etc/systemd/system/docker.service.d/override.conf"
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    register: restart_systemd

  - name: restart systemd
    command: systemctl daemon-reload
    register: restart_docker
    when: restart_systemd.changed

  - name: restart docker
    service:
      name: docker
      state: restarted
    when: restart_docker.changed


