  - name: "install nginx_proxy_packages"
    apt: 
      pkg: "{{ item }}" 
      state: latest
    with_items: nginx_proxy_packages

  - name: install acme-tiny
    git:
      dest: "/usr/local/bin/acme-tiny"
      repo: "https://github.com/diafygi/acme-tiny/"

  - name: create acme-tiny directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ nginx_proxy_static_root}}/acme-challenge"
      - "/etc/acme-tiny"

  - name: install account.key
    copy:
      src: account.key
      dest: /etc/acme-tiny/account.key

  - name: update site.conf
    template:
      src: site.conf.j2
      dest: "/etc/nginx/sites-enabled/{{ item.host }}.conf"
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    with_items: "{{ nginx_proxy_hosts }}"
    register: restart_nginx

  - name: deploy sites
    git:
      dest: "{{ nginx_proxy_static_root}}/{{item.host}}"
      repo: "{{ item.repo }}"
    when: item.repo is defined
    with_items: "{{ nginx_proxy_hosts }}"

  - name: generate keys
    shell: openssl genrsa 4096 > {{ nginx_proxy_ssl_dir }}/{{ item.host }}.key
    args:
      creates: "{{ nginx_proxy_ssl_dir }}/{{ item.host }}.key"
    when: item.ssl is defined
    with_items: "{{ nginx_proxy_hosts }}"
 
  - name: generate CSRs
    shell: openssl req -new -sha256 -key {{ nginx_proxy_ssl_dir }}/{{ item.host }}.key -subj '/C=US/ST=Massachusetts/L=Acton/O={{ item.host }}/OU=website/CN={{ item.host }}/subjectAltName=DNS:{{item.host}}{% if item.aliases is defined %}{% for alias in item.aliases %},DNS:{{ alias }}{% endfor %}{% endif %}/' > {{ nginx_proxy_ssl_dir }}/{{ item.host }}.csr
    args:
      creates: "{{ nginx_proxy_ssl_dir }}/{{ item.host }}.csr"
    when: item.ssl is defined
    with_items: "{{ nginx_proxy_hosts }}"

  - name: download intermediary cert
    get_url:
      url: https://letsencrypt.org/certs/lets-encrypt-x1-cross-signed.pem
      dest: /etc/acme-tiny/intermediate.pem
 
  - name: sign certificates
    shell: python /usr/local/bin/acme-tiny/acme_tiny.py --account-key /etc/acme-tiny/account.key --csr {{ nginx_proxy_ssl_dir }}/{{ item.host }}.csr --acme-dir {{ nginx_proxy_static_root}}/acme-challenge > {{ nginx_proxy_ssl_dir }}/{{ item.host }}-host.crt
    args:
      creates: "{{ nginx_proxy_ssl_dir }}/{{ item.host }}-host.crt"
    when: item.ssl is defined
    with_items: "{{ nginx_proxy_hosts }}"

  - name: append intermediary certificates
    shell: cat {{ nginx_proxy_ssl_dir }}/{{ item.host }}-host.crt /etc/acme-tiny/intermediate.pem > {{ nginx_proxy_ssl_dir }}/{{ item.host }}.pem
    args:
      creates: "{{ nginx_proxy_ssl_dir }}/{{ item.host }}.pem"
    when: item.ssl is defined
    with_items: "{{ nginx_proxy_hosts }}"
 
  - name: restart nginx
    service:
      name: nginx
      state: restarted
    when: restart_nginx.changed

