  - include_vars: vars/secrets.yml 

  - name: "install nginx_proxy_packages"
    apt: 
      pkg: "{{ item }}" 
      state: latest
    with_items: nginx_proxy_packages

  - name: install acme-tiny
    git:
      dest: "/usr/local/bin/acme-tiny"
      repo: "https://github.com/diafygi/acme-tiny/"

  - name: create acme-tiny directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ nginx_proxy_static_root}}/acme-challenge"
      - "/etc/acme-tiny"

  - name: install account.key
    template:
      src: account.key.j2
      dest: /etc/acme-tiny/account.key
      owner: root
      group: root
      mode: u=r

  - name: update default.conf
    template:
      src: default.conf.j2
      dest: "/etc/nginx/sites-enabled/default"
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    register: restart_nginx

  - name: update site.conf
    template:
      src: site.conf.j2
      dest: "/etc/nginx/sites-enabled/{{ item.key }}.conf"
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    with_dict: "{{ nginx_proxy_hosts }}"
    register: restart_nginx

  - name: deploy sites
    git:
      dest: "{{ nginx_proxy_static_root }}/{{ item.key }}"
      repo: "{{ item.value.repo }}"
    when: item.value.repo is defined
    with_dict: "{{ nginx_proxy_hosts }}"

  - name: generate keys
    shell: openssl genrsa 4096 > {{ nginx_proxy_ssl_dir }}/{{ item.key }}.key
    args:
      creates: "{{ nginx_proxy_ssl_dir }}/{{ item.key }}.key"
    when: item.value.ssl is defined
    with_dict: "{{ nginx_proxy_hosts }}"
 
  - name: generate CSRs
    shell: 'openssl req -new -sha256 -key {{ nginx_proxy_ssl_dir }}/{{ item.key }}.key -subj "/" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:{{ item.key }}{% if item.value.aliases is defined %}{% for alias in item.value.aliases %},DNS:{{ alias }}{% endfor %}{% endif %}")) > {{ nginx_proxy_ssl_dir }}/{{ item.key }}.csr'
    args:
      executable: "/bin/bash"
      creates: "{{ nginx_proxy_ssl_dir }}/{{ item.key }}.csr"
    when: item.value.ssl is defined
    with_dict: "{{ nginx_proxy_hosts }}"

  - name: download intermediary cert
    get_url:
      url: https://letsencrypt.org/certs/lets-encrypt-x1-cross-signed.pem
      dest: /etc/acme-tiny/intermediate.pem
 
  - name: sign certificates
    shell: python /usr/local/bin/acme-tiny/acme_tiny.py --account-key /etc/acme-tiny/account.key --csr {{ nginx_proxy_ssl_dir }}/{{ item.key }}.csr --acme-dir {{ nginx_proxy_static_root}}/acme-challenge > {{ nginx_proxy_ssl_dir }}/{{ item.key }}-host.crt
    args:
      creates: "{{ nginx_proxy_ssl_dir }}/{{ item.key }}-host.crt"
    when: item.value.ssl is defined
    with_dict: "{{ nginx_proxy_hosts }}"

  - name: append intermediary certificates
    shell: cat {{ nginx_proxy_ssl_dir }}/{{ item.key }}-host.crt /etc/acme-tiny/intermediate.pem > {{ nginx_proxy_ssl_dir }}/{{ item.key }}.pem
    args:
      creates: "{{ nginx_proxy_ssl_dir }}/{{ item.key }}.pem"
    when: item.value.ssl is defined
    with_dict: "{{ nginx_proxy_hosts }}"
 
  - name: restart nginx
    service:
      name: nginx
      state: restarted
    when: restart_nginx.changed

